services:
  - type: web
    name: plataforma-monitoreo-ambiental
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true --server.enableCORS false
    plan: free